version: '3.7'
services:

  #PHP Service
  php:
    container_name: ${PROJECT_ID}_php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
      - ~/.composer:/var/www/.composer
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST} remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    depends_on:
      - mariadb

  #Nginx Service
  nginx:
    container_name: ${PROJECT_ID}_nginx
    build:
      context: ./docker/nginx
    ports:
      - ${PROJECT_INTERFACE}:${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    env_file:
      - .env
    depends_on:
      - php

  #MariaDB Service
  mariadb:
    container_name: ${PROJECT_ID}_mariadb
    build:
      context: ./docker/mariadb
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - ${PROJECT_INTERFACE}:${DB_EXTERNAL_PORT}:${DB_PORT}
    volumes:
      - ./docker/mariadb/config:/etc/mysql/conf.d
      - ./docker/mariadb/data:/var/lib/mysql:rw
    env_file:
      - .env

  #Adminer Service
  adminer:
    image: adminer:latest
    container_name: ${PROJECT_ID}_adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
      ADMINER_DESIGN: pepa-linha
    ports:
      - ${PROJECT_INTERFACE}:${ADMINER_PORT}:8080
    env_file:
      - .env
