version: '3.7'
services:

  #PHP Service
  php:
    image: ${COMPOSE_PROJECT_NAME}_php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    user: ${CURRENT_USER}:${CURRENT_GROUP}
    build:
      context: ./docker/php
      args:
        WORKING_DIR: ${WORKING_DIR}
        CURRENT_USER: ${CURRENT_USER}
        CURRENT_GROUP: ${CURRENT_GROUP}
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - ${OUT_HTTP_PORT}:80
      - ${OUT_HTTPS_PORT}:443
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    env_file:
      - .env

  #MariaDB Service
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    build:
      context: ./docker/mariadb
      args:
        CURRENT_USER: ${CURRENT_USER}
        CURRENT_GROUP: ${CURRENT_GROUP}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./docker/mariadb/config:/etc/mysql/conf.d
      - ./docker/mariadb/data:/var/lib/mysql:rw
    env_file:
      - .env

  #Adminer Service
  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
      ADMINER_DESIGN: pepa-linha
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env