name: Laravel Tests
on: [push]

jobs:
  laravel-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4 ]
    services:
      mysql-service:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ipr_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Laravel Setup
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          cp .env.ci .env
          php artisan key:generate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: ipr_test
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          php artisan migrate
          vendor/bin/phpunit
